# Matrices
Matrices for:
- #Hom(F,G)
- #Emb(F,G)
- #Surj(F,G) (surj on edges and vertices)
- #Iso(F,G)
- #Sub(F,G)

In [1]:
# Imports
from globals import *
from homs import *
from generate import *
from spasm import *

In [2]:
# Parameters
GS = [P2, P3, K3, P4, K4]

Homs = matrices(GS, Hom)
Surjs = matrices(GS, Surj)
Subs = matrices(GS, Sub)
Isos = matrices(GS, Iso)
Embs = matrices(GS, Emb)

(0, 1)
(1, 0)
(0, 1, 0)
(1, 0, 1)
(0, 1, 2)
(2, 1, 0)
(0, 1, 2)
(0, 2, 1)
(1, 0, 2)
(1, 2, 0)
(2, 0, 1)
(2, 1, 0)
(0, 1, 0, 1)
(1, 0, 1, 0)
(0, 1, 2, 1)
(1, 0, 1, 2)
(1, 2, 1, 0)
(2, 1, 0, 1)
(0, 1, 2, 0)
(0, 2, 1, 0)
(1, 0, 2, 1)
(1, 2, 0, 1)
(2, 0, 1, 2)
(2, 1, 0, 2)
(0, 1, 2, 3)
(3, 2, 1, 0)
(0, 1, 2, 3)
(0, 1, 3, 2)
(0, 2, 1, 3)
(0, 2, 3, 1)
(0, 3, 1, 2)
(0, 3, 2, 1)
(1, 0, 2, 3)
(1, 0, 3, 2)
(1, 2, 0, 3)
(1, 2, 3, 0)
(1, 3, 0, 2)
(1, 3, 2, 0)
(2, 0, 1, 3)
(2, 0, 3, 1)
(2, 1, 0, 3)
(2, 1, 3, 0)
(2, 3, 0, 1)
(2, 3, 1, 0)
(3, 0, 1, 2)
(3, 0, 2, 1)
(3, 1, 0, 2)
(3, 1, 2, 0)
(3, 2, 0, 1)
(3, 2, 1, 0)


In [3]:
# Hom = Surj * Sub
# Good Basis - Page 14

SurjSub = np.matmul(Surjs,Subs)

print("Hom :", Homs)
print("------------------------")
print("Surj * Sub :", SurjSub)
print("------------------------")
print(Homs == SurjSub)

Hom : [[  2.   4.   6.   6.  12.]
 [  2.   6.  12.  10.  36.]
 [  0.   0.   6.   0.  24.]
 [  2.   8.  24.  16. 108.]
 [  0.   0.   0.   0.  24.]]
------------------------
Surj * Sub : [[  2.   4.   6.   6.  12.]
 [  2.   6.  12.  10.  36.]
 [  0.   0.   6.   0.  24.]
 [  2.   8.  24.  16. 108.]
 [  0.   0.   0.   0.  24.]]
------------------------
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [4]:
# Emb(H -> G) = Hom(H -> G) - sum_f in Spasm \ H Emb(F -> G)
# A = B - C

H = P5
spa = spasm(H)

G1 = K5
G2 = P5 
G3 = K6

A = Emb(H, G1)
B = Hom(H, G1)

C = 0

for s in spa:
    C += Emb(s, G1)

print(A, B, C)


120 1280 1280


In [5]:
Ks = [P5, K5, K6]#, K6, K5s, K7]

for K in Ks:
    print("======================")
    print(K)
    L = Sub(P5, K)
    R = [0.5 * Hom(P5, K)]
    R.append(- 0.5* Hom(C4, K))
    R.append(- 0.5* Hom(S4, K))
    R.append(- Hom(K3s, K))
    R.append(-Hom(P4, K)) 
    R.append(3/2*Hom(K3, K))
    R.append(5/2*Hom(P3, K))
    R.append(- Hom(P2, K))
    
    R = sum(R)

    print(L, R)
    if L == R:
        print('Yes')
    else:
        print('No')

Graph with 5 nodes and 4 edges
1.0 1.0
Yes
Graph with 5 nodes and 10 edges
60.0 60.0
Yes
Graph with 6 nodes and 15 edges
360.0 360.0
Yes


In [6]:
print(sorted("321"))

['1', '2', '3']


In [7]:
Ks = [P5, K5]#, K6, K5s, K7]

for K in Ks:
    print("======================")
    print(K)
    L = Hom(P5, K)
    Homs = Emb(P5, K) + Emb(C4, K)
    Homs += Emb(S4, K) + 2*Emb(K3s, K)
    Homs += 2*Emb(P4, K) + 3*Emb(K3, K)
    Homs += 4*Emb(P3, K) + Emb(P2, K)
    print(L, Homs)
    if L == Homs:
        print('Yes')
    else:
        print('No')

Graph with 5 nodes and 4 edges
42 42
Yes
Graph with 5 nodes and 10 edges
1280 1280
Yes


In [8]:
import math
H = P5
Gs = [K5, K6]#, K5]#, K6, K5s, K7]

for G in Gs:
    print("======================")
    
    L = Sub(H, G) * Iso(H, H)
    S = spasm(H)
    R = 0
    
    # sum over all partitions p
    for s in S:
        n = H.number_of_nodes()
        m = s.number_of_nodes()
        
        val_1 = (-1)**(n - m)
        
        # prod over all Blocks B in p
        val_2 = 1

        for i in s.graph["p"]:
            val_2 *= math.factorial( abs(i) - 1)
        
        
        # Hom( H/p -> G)
        val_3 = Hom(s, G)
        
        #print(s.number_of_nodes())
        print(val_1)
        #print(val_2)
        #print(val_3)
        print("--------")
        R += (val_1 * val_2 * val_3)
        
    print("L :", L)
    print("R :", R)
    
    

-1
--------
1
--------
1
--------
1
--------
1
--------
-1
--------
1
--------
-1
--------
1
--------
1
--------
-1
--------
-1
--------
-1
--------
-1
--------
1
--------
L : 120.0
R : 120
-1
--------
1
--------
1
--------
1
--------
1
--------
-1
--------
1
--------
-1
--------
1
--------
1
--------
-1
--------
-1
--------
-1
--------
-1
--------
1
--------
L : 720.0
R : 720


In [9]:
H = P5
Gs = [K6]

for G in Gs:

    L = Sub(H, G) * Iso(H, H)
    S = spasm(H)
    """
    S = []
    for s in S2:
        if not nx.is_isomorphic(s, H):
            S.append(s)
    """
    R = 0
    
    
    # sum over all partitions p
    for s in S:
        n = H.number_of_nodes()
        m = s.number_of_nodes()
        
        val_1 = (-1)**(n - m)
        
        # prod over all Blocks B in p
        val_2 = 1

        for i in s.graph["p"]:
            print(i)
            val_2 *= math.factorial( abs(i) - 1)

        
        # Hom( H/p -> G)
        val_3 = Hom(s, G)

        R += (val_1 * val_2 * val_3)
    print(L, R)

3
2
2
2
1
1
2
2
3
1
1
2
2
1
1
2
1
1
2
1
2
1
1
2
1
2
2
1
2
2
1
1
2
1
1
2
1
1
1
2
1
1
1
2
1
1
1
1
1
1
1
1
720.0 720


In [10]:
# (13) Surj(H->F) = Aut(F) * sum_p [A] [ H/p iso F]

H = P5
Fs = [P3, P4, P5, K3, K4]

for F in Fs:
    
    S = spasm(H)
    
    L = Surj(H, F)

    r1 = Iso(F, F)

    
    r2 = 0
    for s in S:
        if nx.is_isomorphic(s, F):
            r3 = 1
            #for n in s.nodes():
            #    r3 *= math.factorial( abs(s.nodes[n]["part"]) - 1)
            r2 += r3
    R = r1 * r2
    print("========")
    print(L)
    print(R)      
    

(0, 1, 0, 1, 2)
(0, 1, 2, 1, 2)
(1, 0, 1, 2, 1)
(1, 2, 1, 0, 1)
(2, 1, 0, 1, 0)
(2, 1, 2, 1, 0)
6
8
(0, 1, 2, 3, 2)
(1, 0, 1, 2, 3)
(2, 3, 2, 1, 0)
(3, 2, 1, 0, 1)
4
4
(0, 1, 2, 3, 4)
(4, 3, 2, 1, 0)
2
2
(0, 1, 0, 2, 1)
(0, 1, 2, 0, 2)
(0, 1, 2, 1, 0)
(0, 2, 0, 1, 2)
(0, 2, 1, 0, 1)
(0, 2, 1, 2, 0)
(1, 0, 1, 2, 0)
(1, 0, 2, 0, 1)
(1, 0, 2, 1, 2)
(1, 2, 0, 1, 0)
(1, 2, 0, 2, 1)
(1, 2, 1, 0, 2)
(2, 0, 1, 0, 2)
(2, 0, 1, 2, 1)
(2, 0, 2, 1, 0)
(2, 1, 0, 1, 2)
(2, 1, 0, 2, 0)
(2, 1, 2, 0, 1)
18
18
0
0


In [21]:
def Surj(F, G):
    m, n = F.number_of_nodes(), G.number_of_nodes()
    perm = list(itertools.product([i for i in range(n)], repeat=m))
    perm = [per for per in perm if (len(set(per)) == n)]
    cnt = 0
    for per in perm:
        homomorphism = True
        for edge in F.edges():
            if not (per[edge[0]], per[edge[1]]) in G.edges():
                homomorphism = False
                break
        if homomorphism:
            edges = []
            for g in F.edges():
                x = (per[g[0]], per[g[1]])
                x1 = list(x)
                x1.sort()
                edges.append(x1)
            edges = list(edges for edges,_ in itertools.groupby(edges))
            
            new_edges = []
            for elem in edges:
                if elem not in new_edges:
                    new_edges.append(elem)
            edges = new_edges
            if not (len(G.edges()) == len(edges)):
                homomorphism = False
        if homomorphism:
            cnt += 1
            
    return cnt  

k = Surj(P5, P3)
print(k)




8
